### ISSUE TITLE
Last line of lesson suggests that case statements will be discussed in upcoming lessons, but they are not covered in any further lessons 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/conditional-readme#16]
Student in bootcamp-prep track was expecting to find a lesson on Ruby case statements due to this line, but there doesn't seem to be any further information about case statements. @aturkewi

**Comment by Joll59** [comment]
@kwebster2 
Case statements are discussed in a later lesson found [here].(https://github.com/learn-co-students/case-statements-readme-web-1116)
