### ISSUE TITLE
Results come in as 0 examples, 0 failures, 1 error but I don't know if I've done this lab correctly

### ISSUE THREAD

**Issue by toron93** [learn-co-curriculum/conditional-readme#17]

**Comment by maxwellbenton** [comment]
Hi @toron93,

Thank you for your feedback. This lesson is a readme and has no tests. We are in the process of updating these materials and have added a note in this lesson to use IRB to follow along with the examples, which should resolve this issue.

If you do not feel this has resolved the problem you experienced, please reopen this issue.
