### ISSUE TITLE
if true examples are contrived

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/conditional-readme#9]
I don't love using "if true" and "if false" as the initial examples, because they don't really give a good sense of what conditionals are used for. "true always evaluates to true" is not super intuitive or informative to beginners.

**Comment by aviflombaum** [comment]
I think it's good for now but agree, it should be re-written. @AnnJohn want to give to someone or even write your own because you :metal: (rock).

**Comment by jmburges** [comment]
double agreed. Let's have simple things like `5>2` or better `"joe".starts_with?("j")`

**Comment by AnnJohn** [comment]
Updated.
